[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F166AC8DD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6bd27532a8e795d2b57f7c641b355418
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F166AC8E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6bd27532a8e795d2b57f7c641b355418
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F166AC9010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6bd27532a8e795d2b57f7c641b355418